[package]
name = "regex-replace"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11"
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
anyhow = "1.0"
globset = "0.4"

[dev-dependencies]
tempfile = "3.10"
